[build]
  command = "npm run build"
  publish = "app/routes/_index.html"

[dev]
  command = "npm run dev"
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
